=== sowmyatayi/mulesoft_poc/src/Workspace2/pnrcheckin/src/main/resources/api/PNRCheckinRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/PNRCheckinRequest" xmlns:tns="http://www.example.org/PNRCheckinRequest" elementFormDefault="qualified">

    <element name="PNRCheckinReq" type="tns:PNRCheckinReqType"></element>
    
    <complexType name="PNRType">
    	<sequence>
    		<element name="PNRRecordLocator" type="string"></element>
            <element name="ItineraryLegs" type="tns:FlightLegType" maxOccurs="unbounded" minOccurs="1">
    		</element>
            <element name="Passengers" type="tns:PassengerType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="FlightLegType">
    	<sequence>
    		<element name="FlightNumber" type="string"></element>
    		<element name="OperatingCarrierCode" type="string"></element>
    		<element name="DeptAirportCode" type="string"></element>
    		<element name="ArrAirportCode" type="string"></element>
    		<element name="SchDepDate" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="PassengerType">
    	<sequence>
    		<element name="FirstName" type="string"></element>
    		<element name="LastName" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="ItineraryType">
    	<sequence>
    		<element name="Flight" type="tns:FlightLegType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="PNRCheckinReqType">
    	<sequence>
    		<element name="PNR" type="tns:PNRType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== sowmyatayi/mulesoft_poc/src/Workspace2/passengercheckin/src/main/resources/Schemas/PNRCheckinRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:PNRCheckinReq xmlns:tns="http://www.example.org/PNRCheckinRequest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/PNRCheckinRequest PNRCheckinRequest.xsd ">
  <tns:PNR>
    <tns:PNRRecordLocator>ASHFYU</tns:PNRRecordLocator>
    <tns:ItineraryLegs>
      <tns:FlightNumber>100</tns:FlightNumber>
      <tns:OperatingCarrierCode>B6</tns:OperatingCarrierCode>
      <tns:DeptAirportCode>JFK</tns:DeptAirportCode>
      <tns:ArrAirportCode>PIT</tns:ArrAirportCode>
      <tns:SchDepDate>08-23-2018</tns:SchDepDate>
    </tns:ItineraryLegs>
    <tns:Passengers>
      <tns:FirstName>TEST</tns:FirstName>
      <tns:LastName>TEST</tns:LastName>
    </tns:Passengers>
  </tns:PNR>
</tns:PNRCheckinReq>
